version: '3'
services:

  # Networking
  network:
    image: busybox
    hostname: geowave
    network_mode: bridge
    stop_grace_period: 1s
    stop_signal: SIGKILL
    command: "cat"
    tty: true
    ports:
      - "3000:3000"

  admin-ui:
    build:
      dockerfile: dev.Dockerfile
      context: geowave-admin-ui
    network_mode: service:network
    volumes:
      - ./geowave-admin-ui:/root/admin-ui
      - admin-ui.node_modules:/root/admin-ui/node_modules

  admin-api:
    build:
      dockerfile: dev.Dockerfile
      context: geowave-admin-api
    network_mode: service:network
    volumes:
      - ./geowave-admin-api:/root/admin-api

volumes:
  admin-ui.node_modules:
